### ISSUE TITLE
Convert PDF viewer into a control, and polish

### ISSUE THREAD

**Issue by williamparry** [openlawnz/openlawnz-human-refinement-centre#16]
Make the PDF viewer standalone:

- [ ] Clear up the code into the control being its own class that can handle itself being reset (when changing cases). Resetting will also reset the "Find in PDF" control
- [x] "Find in PDF" to handle clicking the "x" for clearing the input, and pressing "Esc" closes it
- [x] Add loading state (ideally with PDF download progress bar)
- [x] Fix dragging minimap behaviour so that if you move off the minimap while dragging it won't select elements on the page

**Comment by danieljimeneznz** [comment]
Write as class component.
