### ISSUE TITLE
Partially handwritten date of judgment

### ISSUE THREAD

**Issue by saddle-dig-crystal** [openlawnz/openlawnz-human-refinement-centre#3]
![image](https://user-images.githubusercontent.com/60917675/84846636-53c81200-b0a3-11ea-858e-f716a09af269.png)

See screenshot. "27th" has not been detected by OCR. Dropdown box offers January 1999 only.

**Comment by strum3nt** [comment]
I think this OCR miss is probably ok - you can select from drop down and manually type "27" in the date box to ensure the correct date is added to the database

**Comment by strum3nt** [comment]
Update - we can actually change the matching to match [XX] day of [Month] [Year] as long as the OCR has picked that up. Have made that change (not pushed to live site yet)

**Comment by strum3nt** [comment]
Fixed
