### ISSUE TITLE
Function: "click, drag, add" relevant text to facet

### ISSUE THREAD

**Issue by saddle-dig-crystal** [openlawnz/openlawnz-human-refinement-centre#7]
When considering outcome variable, for example, can we add a function that lets the researcher select the relevant text that justifies their conclusion in relation to the facet. Ie, with the "Candy" decision, highlight text in last sentence of final paragraph ("claim for weekly compensation must fail"), and have that added to data for that facet. 

May also need some way of recording whether claimant is appellant or respondent, although is this already recorded?

**Comment by strum3nt** [comment]
Out of scope of current project
