### ISSUE TITLE
Evidential concept variable issue

### ISSUE THREAD

**Issue by saddle-dig-crystal** [openlawnz/openlawnz-human-refinement-centre#8]
![image](https://user-images.githubusercontent.com/60917675/85350617-adbe5100-b555-11ea-9071-a3fea68a901b.png)

Words in para 16 should be highlighted, unless they have been overlooked by us in the list of words.

**Comment by saddle-dig-crystal** [comment]
Same case from Curtis' screen:

![image](https://user-images.githubusercontent.com/60917675/85350694-ebbb7500-b555-11ea-87fa-08dc52304740.png)

**Comment by saddle-dig-crystal** [comment]
Note that both of us were playing around with the "search case" bar, and I'm not sure if this broke something in the parser.

**Comment by saddle-dig-crystal** [comment]
Have just gone onto the jurisdiction variable and no words are being picked up with red lines, and the previously searched phrase is still highlighted, so seems to be soemthign to do with use of search: 
![image](https://user-images.githubusercontent.com/60917675/85350991-bebb9200-b556-11ea-8911-6c6418824390.png)

**Comment by strum3nt** [comment]
Seems to be resolved - subject to updating of lists of search phrases
